spring:
  applcation:
    name:PawHub
  datasource:
    url: jdbc:mysql://localhost:3306/pawhub
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

mybatis:
  configuration:
<<<<<<< HEAD
    map-underscore-to-camel-case=true:
=======
    map-underscore-to-camel-case: true

file:
  base-path: D:/IDEAproject/backend
>>>>>>> 3c551e171800da51349e9c969fc119aae6263936
